### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, unlink '~/repl.lisp-repl'

### ISSUE THREAD

**Issue by Grubben** [neil-lindquist/SLIMA#50] opened 2021-02-23 19:53 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.14.6
**Thrown From**: [slima](https://github.com/neil-lindquist/slima) package 2.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, unlink '/Users/amc/repl.lisp-repl'

```
At fs.js:126

Error: ENOENT: no such file or directory, unlink '/Users/amc/repl.lisp-repl'
    at Object.unlinkSync (fs.js:976:3)
    at REPLView.module.exports.REPLView.destroy (/packages/slima/lib/slima-repl-view.coffee:670:10)
    at REPLView.destroy (/packages/slima/lib/slima-repl-view.coffee:1:1)
    at SlimaView.module.exports.SlimaView.destroyRepl (/packages/slima/lib/slima-view.coffee:30:13)
    at /packages/slima/lib/slima.coffee:218:17)
    at /packages/slima/node_modules/swank-client/lib/client.js:78:22)
    at Socket.emit (events.js:200:13)
    at TCP.<anonymous> (net.js:586:12)
```

### Commands

```
     -1:24.9.0 core:confirm (input.hidden-input)
     -1:24.9.0 slime:expand (input.hidden-input)
     -1:23.3.0 command-palette:toggle (input.hidden-input)
     -1:21.7.0 core:move-down (input.hidden-input)
     -1:21.4.0 core:confirm (input.hidden-input)
     -1:21.4.0 slime:start (input.hidden-input)
     -1:18.9.0 slime:compile-buffer (input.hidden-input)
     -0:56.5.0 core:move-left (input.hidden-input)
 15x -0:53.8.0 core:move-right (input.hidden-input)
     -0:51.6.0 core:move-left (input.hidden-input)
     -0:45.3.0 slime:compile-buffer (input.hidden-input)
     -0:42.2.0 core:save (input.hidden-input)
     -0:40.8.0 slime:compile-buffer (input.hidden-input)
  2x -0:15.2.0 editor:delete-to-beginning-of-word (input.hidden-input)
  2x -0:13.9.0 core:backspace (input.hidden-input)
  2x -0:11.1.0 slime:compile-buffer (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python-jedi 1.10.3-0 
language-lisp 0.2.0 
slima 2.7.0 
```

**Comment by neil-lindquist** [comment] 2021-02-26 19:50
I'm unsure how to reproduce this issue.  What are you doing leading up to the error?

**Comment by neil-lindquist** [comment] 2021-04-24 01:29
I'm going to close this issue, since I don't know how to reproduce it.

**Closed by neil-lindquist** 2021-04-24 01:29 UTC
Labels: bug, question

**Comment by jack23247** [comment] 2022-01-07 21:10
Looks like this happens if you change your project folder after you've already started your sbcl instance. If you then go on Packages > SLIMA > Lisp Process > Quit, the extension won't find `repl.lisp-repl` and it will throw this error.
