### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by cbaggers** [neil-lindquist/SLIMA#9] opened 2019-04-08 08:47 UTC
**steps to reproduce**:

1. start repl
2. focus repl
3. hold ctrl and press the down arrow key (the `CL-USER>` prompt should turn grey)
4. press the return key

This is very easy to do when new to Atom, i;ve seen this 'Pane has been destroyed' error a bunch of times now and I assume it's due to mistyping, there could be other issues too.

Thanks for working on this project. Good luck!

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Home
**Thrown From**: [slima](https://github.com/neil-lindquist/slima) package 1.0.0

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At C:\Users\Baggers\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11

Error: Pane has been destroyed
    at Pane.activate (C:/Users/Baggers/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:463448)
    at /packages/slima/lib/slima-repl-view.coffee:374:17
```

### Commands

```
     -1:09.5.0 editor:newline (input.hidden-input)
  2x -1:06.0 autocomplete-plus:confirm (input.hidden-input)
     -1:03.6.0 editor:newline (input.hidden-input)
  2x -1:00.7.0 atomic-emacs:previous-line (input.hidden-input)
  2x -0:59.2.0 atomic-emacs:next-line (input.hidden-input)
     -0:57.6.0 editor:move-line-up (input.hidden-input)
     -0:56.9.0 editor:move-line-down (input.hidden-input)
     -0:55.2.0 editor:newline (input.hidden-input)
     -0:54.1.0 editor:consolidate-selections (input.hidden-input)
     -0:54.1.0 core:cancel (input.hidden-input)
     -0:40.1.0 slime:disconnect (input.hidden-input)
     -0:37.4.0 slime:restart (input.hidden-input)
     -0:22.1.0 slime:start (input.hidden-input)
     -0:13.7.0 editor:move-line-up (input.hidden-input)
     -0:13.2.0 editor:move-line-down (input.hidden-input)
     -0:12.1.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atomic-emacs 0.13.0 
emacs-plus 0.12.0 
language-lisp 0.2.0 
lisp-paredit 0.6.0 
slima 1.0.0 
```

**Comment by neil-lindquist** [comment] 2019-04-08 18:57
I believe the issue was that ctrl-down is mapped to swap two lines, which ends up breaking the REPL.  I modified the keymap, which should prevent this.

**Comment by Sokolov57** [comment] 2019-04-15 18:37
No, it's not only that. 
I can reproduce this when I try to use `step` to debug something. Instead of creating additional buffer (as in emacs), it instantly pops ups this, and repl hangs.

**Comment by neil-lindquist** [comment] 2019-04-15 19:11
What steps are you taking to reach that?  I tried a quick test with `step` in a fresh REPL and it didn't crash:

```
CL-USER> (defun foo (bar) (* 42 (1+ bar)))
FOO

CL-USER> (step (foo 4))
```
*Dropped into the debugger here, then I used one of the step restarts*
```
210

CL-USER> 
```

**Comment by Sokolov57** [comment] 2019-04-15 19:27
No, I guess you should add (declare (optimize (debug 3))), otherwise it
really doesn't do anything.

**Comment by neil-lindquist** [comment] 2019-04-15 22:38
Even with debug set to 3, it works correctly for me (`(defun foo (bar) (declare (optimize (debug 3))) (* 42 (1+ bar)))`).  Can you step through that function?  Is there a specific function this is failing on?  Also, are you still using SLIMA 1.0.0 and Atom 1.35.1 as per your original post or have you updated one or both of them?

**Comment by Sokolov57** [comment] 2019-04-15 22:48
Nono, I update everything. 
Okay now this doesn't show up, and I cannot reproduce it by doing the same thing. I swear it happened tho. Sorry for disturbing, I just really care about this package.

**Comment by neil-lindquist** [comment] 2019-04-16 01:26
It might have partially been caused by not updating [swank-client](https://www.npmjs.com/package/swank-client) quite right initially on Sunday or a change to the debugger internals.  Either way, I'd rather hear about a non-bug than not hear about a real bug.  I'll close this issue for now, unless it comes up again.

**Closed by neil-lindquist** 2019-04-16 01:26 UTC
Labels: bug
