### ISSUE TITLE
dead repl input after lisp restart

### ISSUE THREAD

**Issue by bopbud** [neil-lindquist/SLIMA#45] opened 2020-08-24 21:12 UTC
Restarting lisp without closing old repl tab doesn't take keyboard input in the repl
This is reproducible on my system:
1. slima->lisp-process->start
;; creates new repl
2. quit lisp in repl:  "(quit)" or, 2a:  slima->lisp-process->quit from the slima menu
3. slima->lisp-process->start
;; " Connected to lisp -code away"
4. now the repl will not accept keyboard input.  I have to close the old repl tab and start a lisp again to create a new repl, then it works
(I don't know if this is an Atom issue)
Thanks
---
ccl v 1.10
slime v 2.26
Kubuntu 20.04

**Comment by neil-lindquist** [comment] 2020-08-25 01:16
I'm guessing something doesn't get reset quite right.

You should be able to use slima->lisp-process->restart as a work around.

**Comment by neil-lindquist** [comment] 2020-08-25 01:42
I think I've written a fix for this in the master branch.
However, I want to review the code with fresh eyes, so I'm not publishing it quite yet.  [You can test the code if your interested](https://github.com/neil-lindquist/SLIMA/wiki/Using-Development-Versions-of-SLIMA), otherwise using `restart` should work until I get this published.

**Comment by bopbud** [comment] 2020-08-25 07:15
FWIW:  slima->lisp-process->restart gives the error message: "Only swank servers created by slima can be restarted" I don't have slime running anywhere else.
Thanks again Neil.  I haven't had time to test the new code, but since you're making a fix, you might like to know that restart doesn't work for me.
George

**Comment by neil-lindquist** [comment] 2020-08-25 12:17
Well, that's a problem since the fix for the `start` problem involves calling `restart`.
I'm assuming you start the initial server through SLIMA, is that correct?
And does restart fail if you eval'ed `(quit)`, quit through SLIMA's menu, or after both situations?

**Comment by bopbud** [comment] 2020-08-25 19:10
I do start the swank server through SLIMA.  And yes, after quitting either through the SLIMA menu or the REPL produces the same error.  Here is another test, FWIW:
lisp-process->quit: "Disconnected from lisp"
lisp-process->connect:  "Code away" ==> now I have a live REPL
lisp-process->quit: "Disconnected from lisp"
lisp-process->connect: "couldn't connect to lisp.  Did you start a lisp swank server?" 
lisp-process->restart: "Only swank servers ..."
lisp-process->start: "couldn't connect to lisp.  Did you start a lisp swank server?" 
lisp-process->start: "Code away" ==> now I have a live REPL after the second try (this was typical behavior for atom-slime)

I came across the initial problem because I'm working on a program that quits lisp when it ends.

**Comment by bopbud** [comment] 2020-08-25 22:25
While you're looking into this, is it possible to keep the same lisp buffer/tab around between lisp restarts instead of restarting with a new /buffertab? It is convenient to have a history of the lisp session around for review and copy and paste, a la emacs.

**Comment by neil-lindquist** [comment] 2020-09-01 02:57
After having a chance to look at this again, I'm unable to reproduce your most recent example. (I was able to reproduce and fix the one posted after I closed the issue).
However, I have improving a number of the related conditionals and fixed one related bug.  So, start/restart should work after calling quit.
With regard to needing run start twice, you may be able to fix that by increasing "Number of connection attempts to make with the swank server (0.2s per attempt)" in Slima's settings.  This allows Swank more time to get started before giving up.

I'm still confused on how you can connect to the Swank server after calling quit.  I'd be interesting in seeing what gets printed to the console when this happens.  You can open it with `toggle dev tools` from the command palette (ctrl-shift-p).  Also, enabling "Show the Swank messages in the JavaScript console" from Slima's settings might provide useful information.


Finally, adding an option to retain the console on restart shouldn't be hard to add.

**Comment by bopbud** [comment] 2020-09-05 00:36
Neil,
I increased the connection attempts to 15 and the need for multiple restarts is gone.  It seems you haven't made your fixes for the initial dead REPL problem official yet. Apologies, but I have not been able to reproduce my recent example either, though I'm sure I tried it several times.  Perhaps I was dizzy and chose "start" instead of "connect" after quitting.  The fix for the dead REPL will be welcome as well as retaining the old lisp buffer on restart.
Thanks again

**Comment by neil-lindquist** [comment] 2020-09-05 17:13
That's good to here that the need for multiple restarts is fixed and the the rest of the behavior in the example doesn't happen enough to cause problems (whatever the ultimate reason).

And none of the patches have been made into an official release yet since I wanted to get all of the relevant behavior fixed in one go.  But I think it's looking good and I've added the option for not clearing the REPL.  So, I'll make the release after a final code review and test (hopefully tonight).

**Comment by neil-lindquist** [comment] 2020-09-06 01:52
The changes are published, so this hopefully should be fixed.  Thank you for bringing these issues to my attention.

**Closed by neil-lindquist** 2020-09-06 01:52 UTC
Labels: bug
